export const SUPPORTED_CHAT_ATTACHMENT_MIME_TYPES = [
  'image/png',
  'image/jpeg',
  'image/jpg',
  'image/gif',
  'application/pdf',
  'text/json',
  'text/xml',
  'application/xml',
  'application/zip',
  'text/csv',
  'text/plain',
  'application/x-7z-compressed',
  'application/x-compressed',
  'application/x-compressed-zip',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/x-drawio',
];

export const GATHER_AI_SUPPORTED_ATTACHMENT_MIME_TYPES = [
  'image/png',
  'image/jpg',
  'image/jpeg',
  'image/gif',
  'text/json',
  'text/xml',
  'text/csv',
  'text/plain',
];
