"""
Tests for validating is_valid_slack_doc_id against get_slack_doc_id.

These tests ensure that:
1. All doc IDs generated by get_slack_doc_id are considered valid by is_valid_slack_doc_id
2. The validation function correctly rejects invalid formats
3. Edge cases are handled properly
"""

from connectors.base.doc_ids import get_slack_doc_id, is_valid_slack_doc_id


class TestSlackDocIdValidation:
    """Test suite for Slack document ID generation and validation consistency."""

    def test_generated_ids_are_valid(self):
        """Test that all IDs generated by get_slack_doc_id pass is_valid_slack_doc_id."""
        test_cases = [
            # Standard channel ID with date
            ("C1234567890", "2024-01-15"),
            ("C0123456789", "2025-12-31"),
            ("CABCDEFGHIJ", "2023-06-15"),
            # DM IDs with date
            ("D1234567890", "2024-01-15"),
            ("D0123456789", "2025-12-31"),
            ("DABCDEFGHIJ", "2023-06-15"),
            # Edge date cases
            ("C1111111111", "1999-01-01"),
            ("C9999999999", "2099-12-31"),
            # Different channel ID formats (all uppercase alphanumeric)
            ("C000000000A", "2024-01-01"),
            ("CZZZZZZZZZ9", "2024-01-01"),
            # Mixed alphanumeric channel IDs
            ("C123ABC456D", "2024-01-01"),
            # Mixed alphanumeric DM IDs
            ("D123ABC456D", "2024-01-01"),
        ]

        for channel_id, date in test_cases:
            doc_id = get_slack_doc_id(channel_id, date)
            assert is_valid_slack_doc_id(doc_id), f"Generated doc ID '{doc_id}' should be valid"

    def test_invalid_slack_doc_id_patterns(self):
        """Test that is_valid_slack_doc_id rejects invalid Slack doc ID patterns."""
        invalid_ids = [
            # Wrong date format
            "C1234567890_24-01-15",
            "C1234567890_2024/01/15",
            "C1234567890_2024.01.15",
            "C1234567890_20240115",
            "C1234567890_2024-1-15",
            "C1234567890_2024-01-1",
            # Invalid channel ID format (lowercase not allowed by current regex)
            "c1234567890_2024-01-15",  # lowercase channel
            "d1234567890_2024-01-15",  # lowercase DM
            "C123456789@_2024-01-15",  # invalid character
            "C123456789-_2024-01-15",  # invalid character
            "D123456789@_2024-01-15",  # invalid character in DM
            "D123456789-_2024-01-15",  # invalid character in DM
            # Missing or wrong separator
            "C1234567890-2024-01-15",
            "C12345678902024-01-15",
            "C1234567890__2024-01-15",
            # Invalid date values (regex doesn't validate date logic, just format)
            # Empty or malformed
            "",
            "_",
            "_2024-01-15",
            "C1234567890_",
            "C1234567890",
            "2024-01-15",
            # Extra content
            "C1234567890_2024-01-15_extra",
            "prefix_C1234567890_2024-01-15",
        ]

        for doc_id in invalid_ids:
            assert not is_valid_slack_doc_id(doc_id), f"Doc ID '{doc_id}' should be invalid"
