name: 'Deploy HubSpot Project'
description: 'Deploy HubSpot project only if files changed'

inputs:
  project_dir:
    description: 'Path to HubSpot project directory'
    required: true
  personal_access_key:
    description: 'HubSpot Personal Access Key'
    required: true
  account_id:
    description: 'HubSpot account ID'
    required: true

outputs:
  deployed:
    description: 'Whether deployment occurred'
    value: ${{ steps.filter.outputs.should_deploy }}

runs:
  using: 'composite'
  steps:
    - name: Check for changes in project directory
      id: filter
      shell: bash
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^${{ inputs.project_dir }}/"; then
          echo "should_deploy=true" >> $GITHUB_OUTPUT
          echo "✅ Changes detected in ${{ inputs.project_dir }}"
        else
          echo "should_deploy=false" >> $GITHUB_OUTPUT
          echo "ℹ️ No changes in ${{ inputs.project_dir }}, skipping deployment"
        fi

    - name: Upload HubSpot Project
      if: steps.filter.outputs.should_deploy == 'true'
      uses: HubSpot/hubspot-project-actions/project-upload@v1.0.0
      with:
        project_dir: ${{ inputs.project_dir }}
        personal_access_key: ${{ inputs.personal_access_key }}
        account_id: ${{ inputs.account_id }}
