"""HubSpot artifact models for ingest pipeline."""

from enum import Enum
from typing import Any

from connectors.base.base_ingest_artifact import ArtifactEntity, BaseIngestArtifact


class HubSpotObjectType(str, Enum):
    """HubSpot CRM object type identifiers."""

    CONTACT = "0-1"
    COMPANY = "0-2"
    DEAL = "0-3"
    TICKET = "0-5"

    EMAILS = "0-49"
    MEETINGS = "0-47"
    TASKS = "0-27"
    COMMUNICATIONS = "0-18"
    CALLS = "0-48"
    NOTES = "0-46"


# Properties to fetch from HubSpot API for companies
HUBSPOT_COMPANY_PROPERTIES = [
    "name",
    "domain",
    "website",
    "industry",
    "numberofemployees",
    "annualrevenue",
    "lifecyclestage",
    "description",
    "country",
    "city",
    "phone",
    "state",
    "createdate",
]

HUBSPOT_CONTACT_PROPERTIES = {
    "hs_additional_emails": "Additional email addresses",
    "hs_data_privacy_ads_consent": "Ads Consent from Forms",
    "hs_all_owner_ids": "All owner IDs",
    "hs_all_team_ids": "All team IDs",
    "hs_all_accessible_team_ids": "All teams",
    "hs_all_contact_vids": "All vids for a contact",
    "annualrevenue": "Annual Revenue",
    "associatedcompanylastupdated": "Associated Company Last Updated",
    "hs_associated_target_accounts": "Associated Target Accounts",
    "hs_avatar_filemanager_key": "Avatar FileManager key",
    "hs_analytics_average_page_views": "Average Pageviews",
    "hs_all_assigned_business_unit_ids": "Brands",
    "hs_social_num_broadcast_clicks": "Broadcast Clicks",
    "hs_buying_role": "Buying Role",
    "engagements_last_meeting_booked_campaign": "Campaign of last booking in meetings tool",
    "city": "City",
    "hs_facebook_ad_clicked": "Clicked Facebook ad",
    "hs_linkedin_ad_clicked": "Clicked LinkedIn Ad",
    "hs_clicked_linkedin_ad": "Clicked on a LinkedIn Ad",
    "closedate": "Close Date",
    "company": "Company Name",
    "company_size": "Company size",
    "hs_contact_creation_legal_basis_source_instance_id": "Contact creation legal basis source instance ID",
    "hs_has_active_subscription": "Contact has an active subscription",
    "hubspot_owner_id": "Contact owner",
    "hs_predictivescoringtier": "Contact priority",
    "hs_is_unworked": "Contact unworked",
    "hs_conversations_visitor_email": "Conversations visitor email",
    "hs_count_is_worked": "Count of engaged contacts",
    "hs_count_is_unworked": "Count of unengaged contacts",
    "country": "Country/Region",
    "hs_country_region_code": "Country/Region Code",
    "createdate": "Create Date",
    "hs_created_by_conversations": "Created By Conversations",
    "hs_created_by_user_id": "Created by user ID",
    "hs_cross_sell_opportunity": "Cross-sell Opportunity",
    "hs_currently_enrolled_in_prospecting_agent": "Currently Enrolled in Prospecting Agent",
    "hs_sequences_is_enrolled": "Currently in Sequence",
    "currentlyinworkflow": "Currently in workflow (discontinued)",
    "hs_customer_agent_lead_status": "Customer Agent Lead Status",
    "date_of_birth": "Date of birth",
    "hs_sa_first_engagement_date": "Date of first engagement",
    "engagements_last_meeting_booked": "Date of last meeting booked in meetings tool",
    "days_to_close": "Days To Close",
    "degree": "Degree",
    "hs_sa_first_engagement_descr": "Description of first engagement",
    "hs_content_membership_registration_domain_sent_to": "Domain to which registration email was sent",
    "email": "Email",
    "hs_email_quarantined": "Email Address Quarantined",
    "hs_email_recipient_fatigue_recovery_time": "Email Address Recipient Fatigue Next Available Sending Time",
    "hs_content_membership_email_confirmed": "Email Confirmed",
    "hs_email_domain": "Email Domain",
    "hs_role": "Employment Role",
    "hs_seniority": "Employment Seniority",
    "hs_sub_role": "Employment Sub Role",
    "hs_employment_change_detected_date": "Employment change detected date",
    "hs_contact_enrichment_opt_out": "Enrichment opt out",
    "hs_contact_enrichment_opt_out_timestamp": "Enrichment opt out timestamp",
    "hs_analytics_revenue": "Event Revenue",
    "hubspotscore": "Events Score",
    "hs_social_facebook_clicks": "Facebook Clicks",
    "hs_facebookid": "Facebook ID",
    "hs_facebook_click_id": "Facebook click id",
    "fax": "Fax Number",
    "field_of_study": "Field of study",
    "hs_first_closed_order_id": "First Closed Order ID",
    "first_conversion_event_name": "First Conversion",
    "first_conversion_date": "First Conversion Date",
    "first_deal_created_date": "First Deal Created Date",
    "firstname": "First Name",
    "hs_first_order_closed_date": "First Order Closed Date",
    "hs_analytics_first_url": "First Page Seen",
    "hs_analytics_first_referrer": "First Referring Site",
    "hs_analytics_first_touch_converting_campaign": "First Touch Converting Campaign",
    "hs_first_outreach_date": "First outreach date",
    "hs_first_subscription_create_date": "First subscription create date",
    "followercount": "Follower Count",
    "hs_full_name_or_email": "Full name or email",
    "gender": "Gender",
    "hs_social_google_plus_clicks": "Google Plus Clicks",
    "hs_google_click_id": "Google ad click id",
    "graduation_date": "Graduation date",
    "hs_is_enriched": "Has been enriched",
    "owneremail": "HubSpot Owner Email (legacy)",
    "ownername": "HubSpot Owner Name (legacy)",
    "hubspot_team_id": "HubSpot Team",
    "hs_first_engagement_object_id": "ID of first engagement",
    "industry": "Industry",
    "hs_inferred_language_codes": "Inferred Language Codes",
    "hs_intent_signals_enabled": "Intent Signals active",
    "hs_intent_paid_up_to_date": "Intent paid up to date",
    "hs_email_bad_address": "Invalid email address",
    "hs_is_merge_revertible": "Is Merge Revertible",
    "hs_is_contact": "Is a contact",
    "hs_email_is_ineligible": "Is globally ineligible",
    "jobtitle": "Job Title",
    "hs_job_change_detected_date": "Job change detected date",
    "job_function": "Job function",
    "hs_journey_stage": "Journey Stage",
    "kloutscoregeneral": "Klout Score",
    "hs_notes_last_activity": "Last Activity",
    "notes_last_updated": "Last Activity Date",
    "notes_last_contacted": "Last Contacted",
    "hs_last_sales_activity_timestamp": "Last Engagement Date",
    "hs_last_sales_activity_type": "Last Engagement Type",
    "hs_last_metered_enrichment_timestamp": "Last Metered Enrichment Timestamp",
    "lastmodifieddate": "Last Modified Date",
    "hs_feedback_last_nps_follow_up": "Last NPS survey comment",
    "hs_feedback_last_survey_date": "Last NPS survey date",
    "hs_feedback_last_nps_rating": "Last NPS survey rating",
    "lastname": "Last Name",
    "hs_analytics_last_url": "Last Page Seen",
    "hs_analytics_last_referrer": "Last Referring Site",
    "hs_latitude": "Latitude",
    "hs_gps_latitude": "Latitudes",
    "hs_predictivecontactscorebucket": "Lead Rating",
    "hs_lead_status": "Lead Status",
    "hs_time_to_first_engagement": "Lead response time",
    "hs_legal_basis": "Legal basis for processing contact's data",
    "lifecyclestage": "Lifecycle Stage",
    "hs_predictivecontactscore_v2": "Likelihood to close",
    "linkedinbio": "LinkedIn Bio",
    "hs_social_linkedin_clicks": "LinkedIn Clicks",
    "linkedinconnections": "LinkedIn Connections",
    "hs_linkedin_url": "LinkedIn URL",
    "hs_linkedinid": "Linkedin ID",
    "hs_live_enrichment_deadline": "Live enrichment deadline",
    "hs_longitude": "Longitude",
    "hs_gps_longitude": "Longitudes",
    "hs_manual_campaign_ids": "Manual campaign ids",
    "marital_status": "Marital Status",
    "hs_marketable_status": "Marketing contact status",
    "hs_marketable_reason_id": "Marketing contact status source name",
    "hs_marketable_reason_type": "Marketing contact status source type",
    "hs_marketable_until_renewal": "Marketing contact until next update",
    "hs_emailconfirmationstatus": "Marketing email confirmation status",
    "hs_email_bounce": "Marketing emails bounced",
    "hs_email_click": "Marketing emails clicked",
    "hs_email_delivered": "Marketing emails delivered",
    "hs_email_open": "Marketing emails opened",
    "hs_email_replied": "Marketing emails replied",
    "engagements_last_meeting_booked_medium": "Medium of last booking in meetings tool",
    "hs_content_membership_email": "Member email",
    "hs_membership_has_accessed_private_content": "Member has accessed private content",
    "hs_content_membership_notes": "Membership Notes",
    "hs_membership_last_private_content_access_date": "Membership last private content access date",
    "hs_merged_object_ids": "Merged Contact IDs",
    "hs_calculated_merged_vids": "Merged vids with timestamps of a contact",
    "message": "Message",
    "military_status": "Military status",
    "mobilephone": "Mobile Phone Number",
    "hs_mobile_sdk_push_tokens": "Mobile Sdk Push Tokens",
    "hs_social_last_engagement": "Most Recent Social Click",
    "hs_notes_next_activity": "Next Activity",
    "notes_next_activity_date": "Next Activity Date",
    "hs_notes_next_activity_type": "Next Activity Type",
    "num_associated_deals": "Number of Associated Deals",
    "numemployees": "Number of Employees",
    "num_conversion_events": "Number of Form Submissions",
    "hs_analytics_num_page_views": "Number of Pageviews",
    "num_notes": "Number of Sales Activities",
    "hs_analytics_num_visits": "Number of Sessions",
    "num_unique_conversion_events": "Number of Unique Forms Submitted",
    "hs_analytics_num_event_completions": "Number of event completions",
    "hs_sequences_actively_enrolled_count": "Number of sequences actively enrolled",
    "hs_sequences_enrolled_count": "Number of sequences enrolled",
    "num_contacted_notes": "Number of times contacted",
    "hs_createdate": "Object create date/time",
    "hs_lastmodifieddate": "Object last modified date/time",
    "hs_analytics_source": "Original Traffic Source",
    "hs_analytics_source_data_1": "Original Traffic Source Drill-Down 1",
    "hs_analytics_source_data_2": "Original Traffic Source Drill-Down 2",
    "hubspot_owner_assigneddate": "Owner assigned date",
    "hs_owning_teams": "Owning Teams",
    "hs_was_imported": "Performed in an import",
    "hs_persona": "Persona",
    "phone": "Phone Number",
    "photo": "Photo",
    "hs_pinned_engagement_id": "Pinned engagement ID",
    "hs_pipeline": "Pipeline",
    "zip": "Postal Code",
    "hs_predictivecontactscore": "Predictive Lead Score",
    "hs_language": "Preferred language",
    "associatedcompanyid": "Primary Associated Company ID",
    "hs_quarantined_emails": "Quarantined Emails",
    "hs_read_only": "Read only object",
    "hs_recent_closed_order_date": "Recent Closed Order Date",
    "recent_conversion_event_name": "Recent Conversion",
    "recent_conversion_date": "Recent Conversion Date",
    "recent_deal_amount": "Recent Deal Amount",
    "recent_deal_close_date": "Recent Deal Close Date",
    "hs_document_last_revisited": "Recent Document Revisit Date",
    "hs_sales_email_last_clicked": "Recent Sales Email Clicked Date",
    "hs_sales_email_last_opened": "Recent Sales Email Opened Date",
    "hs_sales_email_last_replied": "Recent Sales Email Replied Date",
    "hs_object_id": "Record ID",
    "hs_object_source": "Record creation source",
    "hs_object_source_id": "Record creation source ID",
    "hs_object_source_user_id": "Record creation source user ID",
    "hs_object_source_label": "Record source",
    "hs_content_membership_registered_at": "Registered At",
    "hs_registered_member": "Registered member",
    "hs_registration_method": "Registration Method",
    "relationship_status": "Relationship Status",
    "hs_returning_to_office_detected_date": "Returning to office detected date",
    "salutation": "Salutation",
    "school": "School",
    "hs_email_sends_since_last_engagement": "Sends Since Last Engagement",
    "seniority": "Seniority",
    "hs_shared_team_ids": "Shared teams",
    "hs_shared_user_ids": "Shared users",
    "hs_feedback_show_nps_web_survey": "Should be shown an NPS web survey",
    "hs_source_object_id": "Source Object ID",
    "hs_source_portal_id": "Source Portal ID",
    "engagements_last_meeting_booked_source": "Source of last booking in meetings tool",
    "start_date": "Start date",
    "state": "State/Region",
    "hs_state_code": "State/Region Code",
    "hs_content_membership_status": "Status",
    "address": "Street Address",
    "surveymonkeyeventlastupdated": "SurveyMonkey Event Last Updated",
    "hs_timezone": "Time Zone",
    "hs_content_membership_registration_email_sent_at": "Time registration email was sent",
    "total_revenue": "Total Revenue",
    "twitterbio": "Twitter Bio",
    "hs_social_twitter_clicks": "Twitter Clicks",
    "hs_twitterid": "Twitter ID",
    "twitterprofilephoto": "Twitter Profile Photo",
    "twitterhandle": "Twitter Username",
    "hs_sa_first_engagement_object_type": "Type of first engagement",
    "hs_unique_creation_key": "Unique creation key",
    "hs_email_optout": "Unsubscribed from all email",
    "hs_updated_by_user_id": "Updated by user ID",
    "webinareventlastupdated": "Webinar Event Last Updated",
    "website": "Website URL",
    "hs_whatsapp_phone_number": "WhatsApp Phone Number",
    "work_email": "Work email",
    "hs_googleplusid": "googleplus ID",
    "hs_last_sales_activity_date": "last sales activity date old",
    "hs_messaging_engagement_score": "messaging_engagement_score",
    "hs_testpurge": "testpurge",
    "hs_testrollback": "testrollback",
}


HUBSPOT_TICKET_PROPERTIES = {
    "hs_added_to_waitlist_at": "Added to waitlist at",
    "hs_all_associated_contact_companies": "All associated contact companies",
    "hs_all_associated_contact_emails": "All associated contact emails",
    "hs_all_associated_contact_firstnames": "All associated contact first names",
    "hs_all_associated_contact_lastnames": "All associated contact last names",
    "hs_all_associated_contact_mobilephones": "All associated contact mobile phones",
    "hs_all_associated_contact_phones": "All associated contact phones",
    "hs_all_conversation_mentions": "All conversation mentions",
    "hs_all_owner_ids": "All owner IDs",
    "hs_all_team_ids": "All team IDs",
    "hs_all_accessible_team_ids": "All teams",
    "hs_applied_sla_rule_config_at": "Applied SLA Rule Config Date",
    "hs_applied_sla_rule_config_id": "Applied SLA Rule Config ID",
    "hs_applied_sla_schedule_at": "Applied SLA Schedule Date",
    "hs_applied_sla_schedule_id": "Applied SLA Schedule Id",
    "hs_assigned_team_ids": "Assigned Teams",
    "hs_assignment_method": "Assignment Method",
    "hs_auto_generated_from_thread_id": "Auto-generated from thread id",
    "hs_overall_visitor_messages_sentiment": "Average ticket sentiment",
    "hs_overall_visitor_messages_sentiment_score": "Average ticket sentiment score",
    "hs_all_assigned_business_unit_ids": "Brands",
    "hs_ticket_category": "Category",
    "closed_date": "Close date",
    "nps_score": "Conversation NPS score",
    "hs_conversations_originating_thread_id": "Conversations originating thread id",
    "hs_copied_at": "Copied at",
    "hs_copied_by_user": "Copied by user",
    "hs_copied_from_ticket": "Copied ticket",
    "hs_copied_ticket_source": "Copied ticket source",
    "createdate": "Create date",
    "created_by": "Created by",
    "hs_created_by_user_id": "Created by user ID",
    "hs_v2_cumulative_time_in_4": 'Cumulative time in "Closed (Support Pipeline)"',
    "hs_v2_cumulative_time_in_1": 'Cumulative time in "New (Support Pipeline)"',
    "hs_v2_cumulative_time_in_2": 'Cumulative time in "Waiting on contact (Support Pipeline)"',
    "hs_v2_cumulative_time_in_3": 'Cumulative time in "Waiting on us (Support Pipeline)"',
    "hs_custom_inbox": "Custom inbox ID",
    "hs_customer_agent_ticket_status": "Customer Agent ticket status",
    "hs_v2_date_entered_4": 'Date entered "Closed (Support Pipeline)"',
    "hs_v2_date_entered_1": 'Date entered "New (Support Pipeline)"',
    "hs_v2_date_entered_2": 'Date entered "Waiting on contact (Support Pipeline)"',
    "hs_v2_date_entered_3": 'Date entered "Waiting on us (Support Pipeline)"',
    "hs_date_entered_4": "Date entered 'Closed (Support Pipeline)'",
    "hs_date_entered_1": "Date entered 'New (Support Pipeline)'",
    "hs_date_entered_2": "Date entered 'Waiting on contact (Support Pipeline)'",
    "hs_date_entered_3": "Date entered 'Waiting on us (Support Pipeline)'",
    "hs_v2_date_exited_4": 'Date exited "Closed (Support Pipeline)"',
    "hs_v2_date_exited_1": 'Date exited "New (Support Pipeline)"',
    "hs_v2_date_exited_2": 'Date exited "Waiting on contact (Support Pipeline)"',
    "hs_v2_date_exited_3": 'Date exited "Waiting on us (Support Pipeline)"',
    "hs_date_exited_4": "Date exited 'Closed (Support Pipeline)'",
    "hs_date_exited_1": "Date exited 'New (Support Pipeline)'",
    "hs_date_exited_2": "Date exited 'Waiting on contact (Support Pipeline)'",
    "hs_date_exited_3": "Date exited 'Waiting on us (Support Pipeline)'",
    "last_engagement_date": "Date of last engagement",
    "hs_draft_user_ids": "Draft UserIds",
    "hs_email_subject": "Email subject",
    "hs_external_object_ids": "External object ids",
    "hs_file_upload": "File upload",
    "hs_first_assignee_type": "First Assignee Type",
    "first_agent_reply_date": "First agent email response date",
    "hs_first_agent_message_sent_at": "First agent response date",
    "hs_is_one_touch_ticket": "First contact resolution",
    "hs_first_visitor_message_sentiment": "First message sentiment",
    "hs_first_visitor_message_sentiment_score": "First message sentiment score",
    "hs_first_agent_message_sent_by": "First responding rep",
    "hs_form_id": "Form",
    "hs_form_submission_conversion_id": "Form submission conversion ID ",
    "hs_help_desk_onboarding_ticket": "Help Desk onboarding ticket",
    "hs_helpdesk_sort_timestamp": "Helpdesk Sort Timestamp",
    "hs_createdate": "HubSpot create date",
    "hubspot_team_id": "HubSpot team",
    "hs_in_helpdesk": "In Help Desk",
    "hs_in_waitlist": "In Waitlist",
    "hs_inbox_id": "Inbox ID",
    "hs_is_closed_in_time_to_close_sla_count": "Is Closed in Time to Close Sla Count",
    "hs_is_closed_in_time_to_first_response_sla_count": "Is Closed in Time to First Response Sla Count",
    "hs_is_visible_in_help_desk": "Is Visible in Help desk",
    "hs_is_latest_message_failed": "Is latest message failed",
    "hs_is_latest_message_hidden_from_all": "Is latest message hidden from all",
    "hs_ticket_language_ai_tag": "Language",
    "hs_notes_last_activity": "Last Activity",
    "notes_last_updated": "Last Activity Date (Ticket Note)",
    "hs_feedback_last_ces_follow_up": "Last CES survey comment",
    "hs_feedback_last_survey_date": "Last CES survey date",
    "hs_feedback_last_ces_rating": "Last CES survey rating",
    "hs_last_closed_date": "Last Closed Date",
    "notes_last_contacted": "Last Contacted (Ticket Note)",
    "hs_last_email_type": "Last Email Type",
    "hs_lastactivitydate": "Last activity date",
    "hs_lastcontacted": "Last contacted date",
    "last_reply_date": "Last customer reply date",
    "hs_last_email_activity": "Last email activity",
    "hs_last_email_date": "Last email date",
    "hs_last_email_details": "Last email details",
    "hs_last_email_id": "Last email id",
    "hs_last_message_from_visitor": "Last message from visitor",
    "hs_last_message_received_at": "Last message received date",
    "hs_last_visitor_message_sentiment": "Last message sentiment",
    "hs_lastmodifieddate": "Last modified date",
    "hs_last_message_sent_at": "Last response date",
    "hs_latest_message_attachment_types": "Latest message attachment types",
    "hs_latest_message_is_forwarded_email": "Latest message is forwarded email",
    "hs_latest_message_is_thread_comment": "Latest message is thread comment",
    "hs_latest_message_seen_by_agent_ids": "Latest message seen by agent ids",
    "hs_last_visitor_message_sentiment_score": "Latest message sentiment score",
    "hs_latest_message_visible_to_visitor": "Latest message visible to visitor",
    "hs_latest_message_visible_to_visitor_sent_at": "Latest message visible to visitor sent at",
    "hs_v2_latest_time_in_4": 'Latest time in "Closed (Support Pipeline)"',
    "hs_v2_latest_time_in_1": 'Latest time in "New (Support Pipeline)"',
    "hs_v2_latest_time_in_2": 'Latest time in "Waiting on contact (Support Pipeline)"',
    "hs_v2_latest_time_in_3": 'Latest time in "Waiting on us (Support Pipeline)"',
    "hs_merged_object_ids": "Merged Ticket IDs",
    "hs_msteams_message_id": "Microsoft Teams message ID for this ticket.",
    "hs_most_relevant_sla_type": "Most Relevant SLA Type",
    "hs_most_relevant_sla_status": "Most relevant SLA status",
    "nps_follow_up_answer": "NPS follow up",
    "nps_follow_up_question_version": "NPS follow up question",
    "hs_notes_next_activity": "Next Activity",
    "notes_next_activity_date": "Next Activity Date (Ticket Note)",
    "hs_notes_next_activity_type": "Next Activity Type",
    "hs_nextactivitydate": "Next activity date",
    "hs_num_associated_companies": "Number of Associated Companies",
    "hs_num_associated_conversations": "Number of Associated Conversations",
    "num_notes": "Number of Sales Activities",
    "hs_num_times_contacted": "Number of times contacted",
    "num_contacted_notes": "Number of times contacted (Ticket Note)",
    "hs_number_of_touches": "Number of touches",
    "hs_conversations_originating_message_id": "Originating Conversations Message Id",
    "hs_originating_channel_instance_id": "Originating channel account",
    "hs_originating_generic_channel_id": "Originating channel type",
    "hs_originating_email_engagement_id": "Originating email engagement id",
    "hs_outbound_ticket": "Outbound ticket",
    "hubspot_owner_assigneddate": "Owner assigned date",
    "hs_owning_teams": "Owning Teams",
    "hs_was_imported": "Performed in an import",
    "hs_pinned_engagement_id": "Pinned Engagement ID",
    "hs_pipeline": "Pipeline",
    "hs_primary_company": "Primary Company",
    "hs_primary_company_id": "Primary Company ID",
    "hs_primary_company_name": "Primary Company Name",
    "hs_ticket_priority": "Priority",
    "hs_read_only": "Read only object",
    "hs_sales_email_last_replied": "Recent Sales Email Replied Date",
    "hs_object_id": "Record ID",
    "hs_object_source": "Record creation source",
    "hs_object_source_id": "Record creation source ID",
    "hs_object_source_user_id": "Record creation source user ID",
    "hs_object_source_label": "Record source",
    "hs_object_source_detail_1": "Record source detail 1",
    "hs_object_source_detail_2": "Record source detail 2",
    "hs_object_source_detail_3": "Record source detail 3",
    "source_thread_id": "Reference to email thread",
    "source_ref": "Reference to source-specific object",
    "hs_resolution": "Resolution",
    "hs_retroactive_sla_update_at": "Retroactive SLA update at",
    "hs_sla_pause_status": "SLA Pause Status",
    "hs_sla_operating_hours": "SLA operating hours",
    "hs_shared_team_ids": "Shared teams",
    "hs_shared_user_ids": "Shared users",
    "hs_snoozed_by_user_ids": "Snoozed by user IDs",
    "source_type": "Source",
    "hs_source_object_id": "Source Object ID",
    "hs_source_url": "Source url",
    "tags": "Tags",
    "hs_thread_ids_to_restore": "Thread IDs To Restore",
    "hs_ticket_id": "Ticket ID",
    "hs_tag_ids": "Ticket Tags",
    "content": "Ticket description",
    "subject": "Ticket name",
    "hubspot_owner_id": "Ticket owner",
    "hs_ticket_reopened_at": "Ticket reopen date",
    "hs_pipeline_stage": "Ticket status",
    "hs_time_in_4": "Time in 'Closed (Support Pipeline)'",
    "hs_time_in_1": "Time in 'New (Support Pipeline)'",
    "hs_time_in_2": "Time in 'Waiting on contact (Support Pipeline)'",
    "hs_time_in_3": "Time in 'Waiting on us (Support Pipeline)'",
    "hs_time_to_close_sla_at": "Time to Close SLA Due Date",
    "hs_time_to_close_sla_status": "Time to Close SLA Ticket Status",
    "hs_time_to_first_response_sla_at": "Time to First Response SLA Due Date",
    "hs_time_to_first_response_sla_status": "Time to First Response SLA Status",
    "hs_time_to_next_response_sla_at": "Time to Next Response SLA Due Date",
    "hs_time_to_next_response_sla_status": "Time to Next Response SLA Status",
    "time_to_close": "Time to close",
    "hs_time_to_close_in_operating_hours": "Time to close in SLA hours",
    "time_to_first_agent_reply": "Time to first agent email reply",
    "hs_time_to_first_assign": "Time to first assign",
    "hs_time_to_first_rep_assignment": "Time to first rep assignment",
    "hs_time_to_first_response_in_operating_hours": "Time to first response in SLA hours",
    "hs_unique_creation_key": "Unique creation key",
    "hs_updated_by_user_id": "Updated by user ID",
    "hs_user_ids_of_all_notification_followers": "User IDs of all notification followers",
    "hs_user_ids_of_all_notification_unfollowers": "User IDs of all notification unfollowers",
    "hs_user_ids_of_all_owners": "User IDs of all owners",
    "hs_seen_by_agent_ids": "Users interaction",
    "hs_waitlist_routing_targets": "Waitlist routing targets",
    "hs_waitlist_sort_value": "Waitlist sort value",
    "hs_mentioned_note_user_ids": "mentioned_note_user_ids",
    "hs_mentions_user_ids": "mentions_user_ids",
}

# Properties to fetch from HubSpot API for deals
HUBSPOT_DEAL_PROPERTIES = [
    "amount",
    "amount_in_home_currency",
    "closed_lost_reason",
    "closed_won_reason",
    "closedate",
    "createdate",
    "days_to_close",
    "deal_currency_code",
    "dealname",
    "dealstage",
    "description",
    "hs_arr",
    "hs_closed_amount_in_home_currency",
    "hs_deal_stage_probability",
    "hs_forecast_amount",
    "hs_forecast_probability",
    "hs_is_closed",
    "hs_is_closed_won",
    "hs_is_closed_lost",
    "hs_mrr",
    "hs_object_id",
    "hs_primary_associated_company",
    "hs_tcv",
    "hubspot_owner_id",
    "num_associated_contacts",
    "pipeline",
]


HUBSPOT_ACTIVITY_TYPES = ["calls", "emails", "meetings", "notes", "tasks", "communications"]

HUBSPOT_ACTIVITY_EMAIL_PROPERTIES = [
    "hs_email_subject",
    "hs_email_sender_email",
    "hs_email_sender_firstname",
    "hs_email_sender_lastname",
    "hs_email_from_email",
    "hs_email_from_firstname",
    "hs_email_from_lastname",
    "hs_email_bcc_email",
    "hs_email_bcc_firstname",
    "hs_email_bcc_lastname",
    "hs_email_cc_email",
    "hs_email_cc_firstname",
    "hs_email_cc_lastname",
    "hs_email_text",
    "hs_email_html",
    "hs_email_thread_id",
]

HUBSPOT_ACTIVITY_MEETING_PROPERTIES = [
    "hs_meeting_title",
    "hs_meeting_body",
    "hs_guest_emails",
    "hs_meeting_external_url",
    "hs_meeting_location_type",
    "hs_meeting_location",
    "hs_meeting_notetaker_selection",
    "hs_meeting_outcome",
    "hs_meeting_source",
    "hs_meeting_start_time",
    "hs_meeting_end_time",
    "hs_outcome_canceled_count",
    "hs_outcome_completed_count",
    "hs_outcome_no_show_count",
    "hs_outcome_rescheduled_count",
    "hs_outcome_scheduled_count",
    "hs_scheduled_tasks",
]

HUBSPOT_ACTIVITY_TASK_PROPERTIES = [
    "hs_associated_company_labels",
    "hs_associated_contact_labels",
    "hs_marketing_task_category",
    "hs_marketing_task_category_id",
    "hs_task_family",
    "hs_task_body",
    "hs_task_type",
    "hs_task_probability_to_complete",
    "hs_task_priority",
]

HUBSPOT_ACTIVITY_CALL_PROPERTIES = [
    "hs_call_source",
    "hs_call_direction",
    "hs_call_duration",
    "hs_call_location",
    "hs_call_disposition",
    "hs_call_routing_strategy_type",
    "hs_call_status",
    "hs_call_suggested_next_actions",
    "hs_call_summary",
    "hs_call_from_number_nickname",
    "hs_call_from_number",
    "hs_call_primary_deal",
    "hs_call_to_number",
    "hs_call_to_number_nickname",
]

HUBSPOT_ACTIVITY_NOTE_PROPERTIES = [
    "hs_note_body",
    "hs_hd_ticket_ids",
]

HUBSPOT_ACTIVITY_COMMON_PROPERTIES = [
    "hs_createdate",
    "hs_lastmodifieddate",
    "hs_timestamp",
    "hs_activity_type",
]

HUBSPOT_ACTIVITY_ALL_PROPERTIES = (
    HUBSPOT_ACTIVITY_COMMON_PROPERTIES
    + HUBSPOT_ACTIVITY_EMAIL_PROPERTIES
    + HUBSPOT_ACTIVITY_MEETING_PROPERTIES
    + HUBSPOT_ACTIVITY_TASK_PROPERTIES
    + HUBSPOT_ACTIVITY_CALL_PROPERTIES
    + HUBSPOT_ACTIVITY_NOTE_PROPERTIES
)

# Activity Property Names
HUBSPOT_ACTIVITY_PROPERTY_NAMES = {
    "emails": {
        "hs_timestamp": "Activity date",
        "hs_createdate": "Create date",
        "hs_email_bcc_email": "Email BCC Address",
        "hs_email_bcc_firstname": "Email BCC First Name",
        "hs_email_bcc_lastname": "Email BCC Last Name",
        "hs_email_cc_email": "Email CC Address",
        "hs_email_cc_firstname": "Email CC First Name",
        "hs_email_cc_lastname": "Email CC Last Name",
        "hs_email_from_email": "Email From Address",
        "hs_email_from_firstname": "Email From First Name",
        "hs_email_from_lastname": "Email From Last Name",
        "hs_email_sender_email": "Email Sender Address",
        "hs_email_sender_firstname": "Email Sender First Name",
        "hs_email_sender_lastname": "Email Sender Last Name",
        "hs_email_html": "Email body",
        "hs_email_subject": "Email subject",
        "hs_lastmodifieddate": "Last modified date",
        "hs_email_text": "Text",
        "hs_email_thread_id": "Thread ID",
    },
    "calls": {
        "hs_timestamp": "Activity date",
        "hs_call_source": "Call Source",
        "hs_activity_type": "Call and meeting type",
        "hs_call_direction": "Call direction",
        "hs_call_duration": "Call duration",
        "hs_call_location": "Call location",
        "hs_call_disposition": "Call outcome",
        "hs_call_routing_strategy_type": "Call routing strategy type",
        "hs_call_status": "Call status",
        "hs_call_suggested_next_actions": "Call suggested next actions",
        "hs_call_summary": "Call summary",
        "hs_createdate": "Create date",
        "hs_call_from_number_nickname": "From Number Name",
        "hs_call_from_number": "From number",
        "hs_lastmodifieddate": "Last modified date",
        "hs_call_primary_deal": "Primary Deal",
        "hs_call_to_number": "To Number",
        "hs_call_to_number_nickname": "To Number Name",
    },
    "meetings": {
        "hs_timestamp": "Activity date",
        "hs_activity_type": "Call and meeting type",
        "hs_createdate": "Create date",
        "hs_meeting_external_url": "External URL",
        "hs_guest_emails": "Guest Emails",
        "hs_lastmodifieddate": "Last modified date",
        "hs_meeting_location_type": "Location type",
        "hs_meeting_body": "Meeting description",
        "hs_meeting_end_time": "Meeting end time",
        "hs_meeting_location": "Meeting location",
        "hs_meeting_title": "Meeting name",
        "hs_meeting_notetaker_selection": "Meeting notetaker selection",
        "hs_meeting_outcome": "Meeting outcome",
        "hs_meeting_source": "Meeting source",
        "hs_meeting_start_time": "Meeting start time",
        "hs_outcome_canceled_count": "Outcome canceled count",
        "hs_outcome_completed_count": "Outcome completed count",
        "hs_outcome_no_show_count": "Outcome no show count",
        "hs_outcome_rescheduled_count": "Outcome rescheduled count",
        "hs_outcome_scheduled_count": "Outcome scheduled count",
        "hs_scheduled_tasks": "Scheduled tasks",
    },
    "notes": {
        "hs_timestamp": "Activity date",
        "hs_createdate": "Create date",
        "hs_lastmodifieddate": "Last modified date",
        "hs_note_body": "Note body",
        "hs_hd_ticket_ids": "hd_ticket_ids",
    },
    "tasks": {
        "hs_associated_company_labels": "Associated company names or domains",
        "hs_associated_contact_labels": "Associated contact full names or emails",
        "hs_marketing_task_category": "Category",
        "hs_marketing_task_category_id": "Category ID",
        "hs_createdate": "Created at",
        "hs_timestamp": "Due date",
        "hs_lastmodifieddate": "Last modified at",
        "hs_task_priority": "Priority",
        "hs_scheduled_tasks": "Scheduled tasks",
        "hs_task_family": "Task Family",
        "hs_task_body": "Task Notes",
        "hs_task_type": "Task Type",
        "hs_task_probability_to_complete": "Task probability to complete",
    },
    "communications": {
        "hs_timestamp": "Activity date",
        "hs_createdate": "Object create date/time",
        "hs_lastmodifieddate": "Object last modified date/time",
    },
}


class HubspotCompanyArtifact(BaseIngestArtifact):
    """Artifact for HubSpot company data."""

    entity: ArtifactEntity = ArtifactEntity.HUBSPOT_COMPANY
    content: dict[str, Any]  # Company properties
    metadata: dict[str, Any]  # Contains company_id, created_at, updated_at


class HubspotTicketArtifact(BaseIngestArtifact):
    """Artifact for HubSpot ticket data with embedded company and pipeline info."""

    entity: ArtifactEntity = ArtifactEntity.HUBSPOT_TICKET
    content: dict[str, Any]  # Ticket data with pipeline/stage names and company names
    metadata: dict[str, Any]  # Contains ticket_id, pipeline_id, stage_id, company_ids


class HubspotDealArtifact(BaseIngestArtifact):
    """Artifact for HubSpot deal data with embedded company and pipeline info."""

    entity: ArtifactEntity = ArtifactEntity.HUBSPOT_DEAL
    content: dict[str, Any]  # Deal data with pipeline/stage names and company names
    metadata: dict[str, Any]  # Contains deal_id, pipeline_id, stage_id, company_ids


class HubspotDealActivityArtifact(BaseIngestArtifact):
    """Artifact for HubSpot deal activity data."""

    entity: ArtifactEntity = ArtifactEntity.HUBSPOT_DEAL_ACTIVITY
    content: dict[str, Any]  # Deal activity data
    metadata: dict[str, Any]  # Contains deal_activity_id, deal_id, activity_type


class HubspotContactArtifact(BaseIngestArtifact):
    """Artifact for HubSpot contact data with embedded company info."""

    entity: ArtifactEntity = ArtifactEntity.HUBSPOT_CONTACT
    content: dict[str, Any]  # Contact data with company names
    metadata: dict[str, Any]  # Contains contact_id, company_ids
