#!/usr/bin/env python3
"""Interactive CLI for setting up local Slack bot development."""

import json
import sys
import webbrowser
from datetime import datetime
from pathlib import Path
from urllib.parse import quote

# ANSI color codes
GREEN = "\033[0;32m"
BLUE = "\033[0;34m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
NC = "\033[0m"  # No Color


def print_header(text: str) -> None:
    """Print a colored header."""
    print(f"\n{BLUE}{'━' * 60}{NC}")
    print(f"{BLUE}  {text}{NC}")
    print(f"{BLUE}{'━' * 60}{NC}\n")


def print_success(text: str) -> None:
    """Print success message."""
    print(f"{GREEN}✓ {text}{NC}")


def print_error(text: str) -> None:
    """Print error message."""
    print(f"{RED}Error: {text}{NC}")


def print_warning(text: str) -> None:
    """Print warning message."""
    print(f"{YELLOW}{text}{NC}")


def get_project_root() -> Path:
    """Get the project root directory."""
    # This file is in src/cli/, so go up two levels
    return Path(__file__).parent.parent.parent


def validate_url(url: str) -> bool:
    """Validate that the URL starts with http:// or https://."""
    return url.startswith("http://") or url.startswith("https://")


def generate_manifest(webhook_url: str, bot_name: str) -> dict:
    """Generate the Slack app manifest."""
    return {
        "display_information": {
            "name": bot_name,
            "description": "A smart AI with context of our company's data. Tag it or DM to get a response. Powered by Grapevine from Gather.",
            "background_color": "#000000",
        },
        "features": {
            "app_home": {
                "home_tab_enabled": False,
                "messages_tab_enabled": True,
                "messages_tab_read_only_enabled": False,
            },
            "bot_user": {"display_name": bot_name, "always_online": True},
        },
        "oauth_config": {
            "redirect_urls": ["http://localhost:5173/api/slack/oauth/callback"],
            "scopes": {
                "bot": [
                    "channels:join",
                    "channels:history",
                    "channels:read",
                    "chat:write.public",
                    "chat:write",
                    "groups:read",
                    "reactions:read",
                    "reactions:write",
                    "im:read",
                    "team:read",
                    "users:read",
                    "users:read.email",
                    "users.profile:read",
                    "im:history",
                    "im:write",
                    "files:read",
                    "groups:history",
                    "mpim:history",
                    "mpim:read",
                ]
            },
        },
        "settings": {
            "event_subscriptions": {
                "request_url": webhook_url,
                "bot_events": [
                    "channel_created",
                    "member_joined_channel",
                    "message.channels",
                    "message.groups",
                    "message.im",
                    "message.mpim",
                    "reaction_added",
                    "reaction_removed",
                ],
            },
            "interactivity": {"is_enabled": True, "request_url": webhook_url},
            "org_deploy_enabled": False,
            "socket_mode_enabled": False,
            "token_rotation_enabled": False,
        },
    }


def save_env_local(
    project_root: Path, client_id: str, client_secret: str, signing_secret: str
) -> None:
    """Save credentials to .env.local file."""
    env_local_path = project_root / ".env.local"

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""# Local Slack Bot Configuration
# Generated by 'mise configure slack' on {timestamp}
# These values are for local development

SLACK_CLIENT_ID={client_id}
SLACK_CLIENT_SECRET={client_secret}
SLACK_SIGNING_SECRET={signing_secret}
"""

    env_local_path.write_text(content)
    print_success(f"Configuration saved to {env_local_path.relative_to(project_root)}")


def main() -> None:
    """Main entry point for the CLI."""
    print_header("Grapevine Local Slack Bot Setup")

    project_root = get_project_root()

    # Step 1: Get bot name
    print(f"{YELLOW}Step 1: Configure Bot Name{NC}")
    print("Choose a name for your local Slack bot.")
    print()

    bot_name = input("Enter bot name: ").strip()
    if not bot_name:
        print_error("Bot name is required")
        sys.exit(1)

    print_success(f"Bot name: {bot_name}")

    # Step 2: Get webhook URL
    print()
    print(f"{YELLOW}Step 2: Configure Webhook URL{NC}")
    print("You need a public URL for Slack to send webhooks to your local gatekeeper.")
    print("This is typically an ngrok tunnel like: https://abc123.ngrok-free.app")
    print()

    webhook_input = input("Enter your webhook URL: ").strip()

    if not validate_url(webhook_input):
        print_error("URL must start with http:// or https://")
        sys.exit(1)

    # Extract base URL by removing /webhooks/slack if present, and any trailing slashes
    webhook_base_url = webhook_input.rstrip("/")
    if webhook_base_url.endswith("/webhooks/slack"):
        webhook_base_url = webhook_base_url[: -len("/webhooks/slack")]
    webhook_url = f"{webhook_base_url}/webhooks/slack"

    print_success(f"Webhook URL: {webhook_url}")

    # Step 3: Generate manifest and create Slack app
    print()
    print(f"{YELLOW}Step 3: Create Slack App from Manifest{NC}")
    print("Generating Slack app manifest...")

    manifest = generate_manifest(webhook_url, bot_name)
    manifest_json = json.dumps(manifest)
    encoded_manifest = quote(manifest_json)

    slack_app_url = f"https://api.slack.com/apps?new_app=1&manifest_json={encoded_manifest}"

    print_success("Manifest generated")
    print()
    print("Opening Slack app creation page in your browser...")
    print("This will create a new Slack app with the correct configuration.")
    print()

    try:
        webbrowser.open(slack_app_url)
    except Exception:
        print_warning("Could not open browser automatically. Please visit:")
        print(slack_app_url)

    # Step 4: Collect credentials
    print()
    print(f"{YELLOW}Step 4: Configure Credentials{NC}")
    print("After creating the app, you'll see your credentials on the screen.")
    print()

    client_id = input("Enter Client ID: ").strip()
    client_secret = input("Enter Client Secret: ").strip()
    signing_secret = input("Enter Signing Secret: ").strip()

    if not all([client_id, client_secret, signing_secret]):
        print_error("Client ID, Client Secret, and Signing Secret are required")
        sys.exit(1)

    print()
    print_success("Credentials collected")

    # Step 5: Write to .env.local
    print()
    print(f"{YELLOW}Step 5: Saving Configuration{NC}")
    save_env_local(project_root, client_id, client_secret, signing_secret)

    # Step 6: Success message
    print()
    print(f"{GREEN}{'━' * 60}{NC}")
    print(f"{GREEN}  Setup Complete!{NC}")
    print(f"{GREEN}{'━' * 60}{NC}")
    print()
    print(f"{BLUE}Next Steps:{NC}")
    print()
    print("Restart your local development environment:")
    print(f"   {BLUE}mise dev{NC}")
    print()
    print_warning("Important: Make sure your ngrok/tunnel is running and pointing to:")
    print(f"   {BLUE}http://localhost:8001{NC}")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        print_warning("Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print()
        print_error(f"Unexpected error: {e}")
        sys.exit(1)
