apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot
  namespace: grapevine-workers
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    app.kubernetes.io/name: slackbot
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: slackbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slackbot
    spec:
      serviceAccountName: slackbot
      imagePullSecrets:
        - name: priv-docker-registry
      containers:
        - name: slackbot
          image: REGISTRY/grapevine-slackbot:latest
          envFrom:
            - secretRef:
                name: slackbot-secrets
          resources:
            requests:
              cpu: 250m
              memory: '512Mi'
            limits:
              cpu: '1'
              memory: '2Gi'
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            capabilities:
              drop:
                - all
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: slackbot
  namespace: grapevine-workers
  labels:
    app.kubernetes.io/name: slackbot
spec:
  minAvailable: 60%
  selector:
    matchLabels:
      app.kubernetes.io/name: slackbot
