-- Add webhook subscriptions functionality to tenant database
-- This allows tenants to subscribe to webhook notifications for document changes

CREATE TABLE webhook_subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url TEXT NOT NULL,
    secret TEXT NOT NULL, -- Encrypted signing secret for HMAC verification
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL -- User ID who created the subscription
);

-- Ensure each tenant can only have one subscription per URL
CREATE UNIQUE INDEX idx_webhook_subscriptions_url ON webhook_subscriptions(url);

-- Index for efficient queries of active subscriptions
CREATE INDEX idx_webhook_subscriptions_active ON webhook_subscriptions(active);

-- Index for audit/management queries by creator
CREATE INDEX idx_webhook_subscriptions_created_by ON webhook_subscriptions(created_by);

-- Add updated_at trigger to automatically update timestamp on row changes
CREATE OR REPLACE FUNCTION update_webhook_subscriptions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_webhook_subscriptions_updated_at
    BEFORE UPDATE ON webhook_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_webhook_subscriptions_updated_at();

-- Add comments for documentation
COMMENT ON TABLE webhook_subscriptions IS 'Tenant webhook subscriptions for document change notifications';
COMMENT ON COLUMN webhook_subscriptions.url IS 'HTTPS endpoint to receive webhook notifications';
COMMENT ON COLUMN webhook_subscriptions.secret IS 'Encrypted HMAC signing secret (generated by Grapevine)';
COMMENT ON COLUMN webhook_subscriptions.active IS 'Whether this subscription should receive notifications';
COMMENT ON COLUMN webhook_subscriptions.created_by IS 'User ID of the person who created this subscription';