{{if .Hotfix }}Hotfixes{{ else }}Promotes{{ end }} {{ .Commit }} to `{{ .Environment }}` (base: {{ .BaseCommit }}).

{{- $root := . }}
{{- $allApproved := true }}
{{- range .Commits }}
{{- $pr := (index $root.PRs .PR | default (dict)) }}
{{- if not $pr.Approved }}
{{- $allApproved = false }}
{{- break }}
{{- end }}
{{- end }}
{{- if not $allApproved }}

> [!WARNING]
> Not all PRs in this promotion have been approved.
> Please review the unreviewed PRs below before approving this promotion.
{{- end }}
{{- if and .Hotfix (gt (len .PRs) 1) }}

> [!WARNING]
> Environment {{ .Environment }} has other hotfixes present. They have been
> re-applied in this PR. Multiple hotfixes may be potentially dangerous.
{{- end }}

## Changes

{{- range .Commits }}
{{- $pr := (index $root.PRs .PR | default (dict)) }}
{{- $msg := regexSplit "\\n" .Commit.GetCommit.GetMessage -1 | first | replace (printf "(#%d)" .PR) (printf "([#%d](https://app.graphite.dev/github/pr/gathertown/corporate-context/%d))" .PR .PR) }}
{{- $author := .Commit.GetAuthor.GetLogin }}
 * {{ if $pr.Approved }}✅{{ else }}❌{{ end }}   {{ $msg }} by @{{ $author }}
{{- end }}

## Legend

 * ✅ = Approved
 * ❌ = No Approval

---

- [ ] Check this box to update the list of PR(s) in this promotions status(es)

---

Generated by [promote](https://github.com/gathertown/corporate-context/tree/main/.github/actions/promote)