export const linearSlackUserMapping = [
  {
    linearId: '1d91279a-81c4-4129-ba83-d95db6c8feb5',
    linearName: 'cneto@gather.town',
    linearDisplayName: 'cneto',
    linearEmail: 'cneto@gather.town',
    slackUserId: 'U09T7KYQJJD',
    slackUserName: 'cneto',
    slackRealName: 'Ciro',
    slackEmail: 'cneto@gather.town',
  },
  {
    linearId: '4fcc44af-0571-420a-a3bd-ce33f5bf7140',
    linearName: 'alexliu@gather.town',
    linearDisplayName: 'alexliu',
    linearEmail: 'alexliu@gather.town',
    slackUserId: 'U09TG78HGG1',
    slackUserName: 'alexliu',
    slackRealName: 'alexliu',
    slackEmail: 'alexliu@gather.town',
  },
  {
    linearId: '73c826e1-6813-414c-b69d-87f1820dd31e',
    linearName: 'Kristine Medina',
    linearDisplayName: 'kmedina',
    linearEmail: 'kmedina@gather.town',
    slackUserId: 'U09M19CBMU3',
    slackUserName: 'kmedina',
    slackRealName: 'Kristine M.',
    slackEmail: 'kmedina@gather.town',
  },
  {
    linearId: 'ac05c214-aa3a-47f4-9cb3-f895348f7e7e',
    linearName: 'Gautam Kedia',
    linearDisplayName: 'gkedia',
    linearEmail: 'gkedia@gather.town',
    slackUserId: 'U09P6RVHE7P',
    slackUserName: 'gkedia',
    slackRealName: 'gkedia',
    slackEmail: 'gkedia@gather.town',
  },
  {
    linearId: '3b7877f6-6373-4bb5-9aac-023bea12b9eb',
    linearName: 'kschultz@gather.town',
    linearDisplayName: 'konrad',
    linearEmail: 'kschultz@gather.town',
    slackUserId: 'U09M5K80HK8',
    slackUserName: 'kschultz',
    slackRealName: 'Konrad Schultz',
    slackEmail: 'kschultz@gather.town',
  },
  {
    linearId: '568653e6-7285-4ffe-b0af-43fde7141516',
    linearName: 'Jonathas Dantas',
    linearDisplayName: 'jdantas',
    linearEmail: 'jdantas@gather.town',
    slackUserId: 'U09LS7QCAJK',
    slackUserName: 'jdantas',
    slackRealName: 'Jonathas',
    slackEmail: 'jdantas@gather.town',
  },
  {
    linearId: '3a8620f4-d417-408a-b5de-e15edc11a41b',
    linearName: 'Pylon',
    linearDisplayName: 'pylon',
    linearEmail: '6afe2c0d-36ca-4d45-ac62-f91205631968@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '93d50e4f-dea2-427d-987d-492c0a40b922',
    linearName: 'Qlod',
    linearDisplayName: 'qlod',
    linearEmail: '00c8cd7c-d6e2-4528-86b7-a725dbd068cc@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '106afc25-822b-4ccd-ba52-4ad5d73df19a',
    linearName: 'Cursor',
    linearDisplayName: 'cursor',
    linearEmail: 'afd5064f-8c2e-4f60-a91a-2b753321d325@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '620296de-8899-40fe-b1fa-719e702d22cf',
    linearName: 'MCP',
    linearDisplayName: 'mcp',
    linearEmail: '05248ad2-e80f-4f12-ae60-e1e8c385751b@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: 'b84e889e-ff8b-4e9a-88c3-2df762886fe9',
    linearName: 'Remote MCP OAuth',
    linearDisplayName: 'remotemcpoauth',
    linearEmail: 'bfb7ba29-dfb1-46e9-b4d5-231532e4f4d3@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '1b5eb2ea-88a2-42f8-b308-c551b52359dd',
    linearName: 'Notion AI',
    linearDisplayName: 'notionai',
    linearEmail: 'f305bf89-adf0-494b-ba3b-a9e3f9d16054@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '2b9e6f06-3df0-4164-a8d2-41adcc6f065a',
    linearName: 'vibe check',
    linearDisplayName: 'vibecheck',
    linearEmail: '34a755a7-c641-4eec-8dff-6cf5172f0b6a@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '57031e99-ad28-4d55-9182-8fa292bdfc71',
    linearName: 'Chandler Roth',
    linearDisplayName: 'croth',
    linearEmail: 'croth@gather.town',
    slackUserId: 'U08S4NPGX7X',
    slackUserName: 'croth',
    slackRealName: 'Chandler Roth',
    slackEmail: 'croth@gather.town',
  },
  {
    linearId: '6f8a5fc7-ed8c-4a71-887b-70a8c0c48f26',
    linearName: 'Ben Greenier (Core)',
    linearDisplayName: 'bgreenier',
    linearEmail: 'bgreenier@gather.town',
    slackUserId: 'U08S4NLD1SR',
    slackUserName: 'bgreenier',
    slackRealName: 'Ben Greenier (Core)',
    slackEmail: 'bgreenier@gather.town',
  },
  {
    linearId: '85710a8e-a968-49dd-b331-ed39c238ecd2',
    linearName: 'jyavor@gather.town',
    linearDisplayName: 'jyavor',
    linearEmail: 'jyavor@gather.town',
    slackUserId: 'U08RDCGU4US',
    slackUserName: 'jyavor',
    slackRealName: 'Josh Yavor',
    slackEmail: 'jyavor@gather.town',
  },
  {
    linearId: '7959bb33-420f-4af5-b1d3-86ac91e27450',
    linearName: 'kburton@gather.town',
    linearDisplayName: 'kburton',
    linearEmail: 'kburton@gather.town',
    slackUserId: 'U08RDCDR9LJ',
    slackUserName: 'kburton',
    slackRealName: 'Kim Burton',
    slackEmail: 'kburton@gather.town',
  },
  {
    linearId: 'ec8681f2-8c73-4d29-8684-663ff11e082a',
    linearName: 'Devin',
    linearDisplayName: 'devin',
    linearEmail: '86bdc758-43ef-4d48-8d09-dacd3082daf8@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '204d1a6f-867b-4d8d-a670-78bca3fb8021',
    linearName: 'Jack Du',
    linearDisplayName: 'jdu',
    linearEmail: 'jdu@gather.town',
    slackUserId: 'U07ET529QJF',
    slackUserName: 'jdu',
    slackRealName: 'Jack Du',
    slackEmail: 'jdu@gather.town',
  },
  {
    linearId: 'e6449dd4-ac0b-48d5-82a4-9930575805b3',
    linearName: 'Codegen',
    linearDisplayName: 'codegen',
    linearEmail: 'a42115259071c86d28210aa7c97cb32f@oauthapp.linear.app',
    slackUserId: null,
    slackUserName: null,
    slackRealName: null,
    slackEmail: null,
  },
  {
    linearId: '685d0a68-97af-4873-ae4c-8d1e00f69f6e',
    linearName: 'rkauk@gather.town',
    linearDisplayName: 'krey',
    linearEmail: 'rkauk@gather.town',
    slackUserId: 'U08GU0NPG7P',
    slackUserName: 'rkauk',
    slackRealName: 'ryan kauk',
    slackEmail: 'rkauk@gather.town',
  },
  {
    linearId: '51eddc7d-31d2-4983-8e29-c963d9686223',
    linearName: 'Alex Budure',
    linearDisplayName: 'alex-b',
    linearEmail: 'abudure@gather.town',
    slackUserId: 'U08FTUAPCQ2',
    slackUserName: 'abudure',
    slackRealName: 'Alex Budure',
    slackEmail: 'abudure@gather.town',
  },
  {
    linearId: 'c39f54da-ad27-45fa-8ac3-c2232a831918',
    linearName: 'jdallas@gather.town',
    linearDisplayName: 'jdallas',
    linearEmail: 'jdallas@gather.town',
    slackUserId: 'U08CM2PLRAS',
    slackUserName: 'jdallas',
    slackRealName: 'Johnny Dallas',
    slackEmail: 'jdallas@gather.town',
  },
  {
    linearId: 'cae0fdbe-5bab-42a0-bd09-6555257b15d2',
    linearName: 'Austin Liou',
    linearDisplayName: 'austin',
    linearEmail: 'austin@gather.town',
    slackUserId: 'U08A8EV0CLT',
    slackUserName: 'austin',
    slackRealName: 'austin',
    slackEmail: 'austin@gather.town',
  },
  {
    linearId: 'a53ca982-8854-4161-b91a-ad17363f4477',
    linearName: 'David Rios',
    linearDisplayName: 'drios',
    linearEmail: 'drios@gather.town',
    slackUserId: 'U087BT3GUDR',
    slackUserName: 'drios',
    slackRealName: 'David Rios',
    slackEmail: 'drios@gather.town',
  },
  {
    linearId: '7f8b2538-1310-496c-bf15-40a451629286',
    linearName: 'Teresa Farmer',
    linearDisplayName: 'teresa',
    linearEmail: 'teresa@gather.town',
    slackUserId: 'U07RTGM16KH',
    slackUserName: 'teresa',
    slackRealName: 'Teresa Araujo',
    slackEmail: 'teresa@gather.town',
  },
  {
    linearId: '66792a5f-1fbc-4c4b-9fbb-3310dddc2b3c',
    linearName: 'Brent Traut',
    linearDisplayName: 'brent',
    linearEmail: 'brent@gather.town',
    slackUserId: 'U07JFGEL9FD',
    slackUserName: 'brent',
    slackRealName: 'Brent Traut',
    slackEmail: 'brent@gather.town',
  },
  {
    linearId: '877b054c-6281-4f01-a1a0-622870595f1d',
    linearName: 'Brad Cerasani',
    linearDisplayName: 'brad',
    linearEmail: 'brad@gather.town',
    slackUserId: 'U077T0ENR5M',
    slackUserName: 'brad',
    slackRealName: 'Brad Cerasani',
    slackEmail: 'brad@gather.town',
  },
  {
    linearId: '70260bb6-b296-4aac-ba57-58d5bf767002',
    linearName: 'Karen Duran',
    linearDisplayName: 'kduran',
    linearEmail: 'kduran@gather.town',
    slackUserId: 'U075ATKEPV5',
    slackUserName: 'kduran',
    slackRealName: 'Karen Duran',
    slackEmail: 'kduran@gather.town',
  },
  {
    linearId: '1a325cc3-3bd1-436c-9081-20f10c88b7ad',
    linearName: 'Emmett Armstrong',
    linearDisplayName: 'emmett',
    linearEmail: 'onrampdata@gather.town',
    slackUserId: 'U02EKMLRSKU',
    slackUserName: 'onrampdata',
    slackRealName: 'Emmett Armstrong',
    slackEmail: 'onrampdata@gather.town',
  },
  {
    linearId: 'a00a1bc9-3b95-4965-8c3b-1cbbd196ef22',
    linearName: 'Zachary Montoya',
    linearDisplayName: 'zmontoya',
    linearEmail: 'zmontoya@gather.town',
    slackUserId: 'U06RXT2UZQ8',
    slackUserName: 'zmontoya',
    slackRealName: 'Zachary Montoya',
    slackEmail: 'zmontoya@gather.town',
  },
  {
    linearId: 'c2db1e87-b7e1-46c2-9d38-5bf97a30afdc',
    linearName: 'Evan Bakst',
    linearDisplayName: 'ebakst',
    linearEmail: 'ebakst@gather.town',
    slackUserId: 'U06ESV8JJ2W',
    slackUserName: 'ebakst',
    slackRealName: 'Evan Bakst',
    slackEmail: 'ebakst@gather.town',
  },
  {
    linearId: 'd90d6502-e333-452c-9efc-6f55e9c8c559',
    linearName: 'Autumn Moody',
    linearDisplayName: 'amoody',
    linearEmail: 'amoody@gather.town',
    slackUserId: 'U047TJ0L69E',
    slackUserName: 'amoody',
    slackRealName: 'Autumn Moody',
    slackEmail: 'amoody@gather.town',
  },
  {
    linearId: '7d07fdb5-7f66-4c1f-86eb-6b1e103e2581',
    linearName: 'Som Chakrabarti',
    linearDisplayName: 'som',
    linearEmail: 'som@gather.town',
    slackUserId: 'U06EP1Y1RL0',
    slackUserName: 'som',
    slackRealName: 'Som Chakrabarti',
    slackEmail: 'som@gather.town',
  },
  {
    linearId: 'e050aa6e-4a55-43e0-b0f4-780745d1473f',
    linearName: 'Aki Tran',
    linearDisplayName: 'aki',
    linearEmail: 'aki@gather.town',
    slackUserId: 'U067WDR98JZ',
    slackUserName: 'aki',
    slackRealName: 'Aki Tran',
    slackEmail: 'aki@gather.town',
  },
  {
    linearId: 'ca654447-b1fc-4402-8976-8346126692c8',
    linearName: 'Aleks Bahdanovich',
    linearDisplayName: 'aleks',
    linearEmail: 'aleks@gather.town',
    slackUserId: 'U068C0UG9GR',
    slackUserName: 'aleks',
    slackRealName: 'Aleks Bahdanovich',
    slackEmail: 'aleks@gather.town',
  },
  {
    linearId: '4e49bce1-a0f0-42c6-b387-b843f08519c5',
    linearName: 'Bryan Phelps',
    linearDisplayName: 'bphelps',
    linearEmail: 'bphelps@gather.town',
    slackUserId: 'U063W9JB7J6',
    slackUserName: 'bphelps',
    slackRealName: 'Bryan Phelps',
    slackEmail: 'bphelps@gather.town',
  },
  {
    linearId: 'bf54ce2d-0f7b-4779-b40e-a499a38c2dd3',
    linearName: 'Carina Aguilar',
    linearDisplayName: 'carina',
    linearEmail: 'carina@gather.town',
    slackUserId: 'U061C3TDCCC',
    slackUserName: 'carina',
    slackRealName: 'Carina',
    slackEmail: 'carina@gather.town',
  },
  {
    linearId: 'd42b1fcb-f43f-41b7-ac64-48dfef554df0',
    linearName: 'Aaron Cohen',
    linearDisplayName: 'aaron',
    linearEmail: 'aaron@gather.town',
    slackUserId: 'U05MJ9YGNKH',
    slackUserName: 'aaron',
    slackRealName: 'Aaron Cohen',
    slackEmail: 'aaron@gather.town',
  },
  {
    linearId: 'dfd3b587-734c-4762-8c9e-1f6b56a0e31b',
    linearName: 'Steven Yau',
    linearDisplayName: 'steven',
    linearEmail: 'steven@gather.town',
    slackUserId: 'U0571JA1FFD',
    slackUserName: 'steven',
    slackRealName: 'Steven Yau',
    slackEmail: 'steven@gather.town',
  },
  {
    linearId: '7ff3efc2-b5a2-4820-b4b4-7ec1d829e35a',
    linearName: 'Andy Lui',
    linearDisplayName: 'alui',
    linearEmail: 'alui@gather.town',
    slackUserId: 'U04TSCYQG4T',
    slackUserName: 'alui',
    slackRealName: 'Andy Lui',
    slackEmail: 'alui@gather.town',
  },
  {
    linearId: '375d4bb2-cbef-477a-88fc-a8004c029065',
    linearName: 'Katrina Lopez',
    linearDisplayName: 'katrina',
    linearEmail: 'katrina@gather.town',
    slackUserId: 'U02E4SZJQGG',
    slackUserName: 'katrina',
    slackRealName: 'Katrina Lopez',
    slackEmail: 'katrina@gather.town',
  },
  {
    linearId: '1d2d6626-5cf4-4bb0-a48b-203969bba1bc',
    linearName: 'Sam Smith',
    linearDisplayName: 'samsmith',
    linearEmail: 'samsmith@gather.town',
    slackUserId: 'U040B2T929W',
    slackUserName: 'samsmith',
    slackRealName: 'Sam Smith',
    slackEmail: 'samsmith@gather.town',
  },
  {
    linearId: 'aada8c9f-985a-4c45-8468-0e163034d666',
    linearName: 'Morgan Smith',
    linearDisplayName: 'morgan',
    linearEmail: 'morgan@gather.town',
    slackUserId: 'U03NRBX8QH2',
    slackUserName: 'morgan',
    slackRealName: 'Morgan Smith',
    slackEmail: 'morgan@gather.town',
  },
  {
    linearId: '932c0d3c-39cf-4521-abbf-1dc34fe3e73b',
    linearName: 'Jordan Maduro',
    linearDisplayName: 'jordan',
    linearEmail: 'jordan@gather.town',
    slackUserId: 'U03DDV4UNG3',
    slackUserName: 'jordan',
    slackRealName: 'Jordan Maduro',
    slackEmail: 'jordan@gather.town',
  },
  {
    linearId: '965d7d14-b95b-4020-b3a3-7aec180b25d5',
    linearName: 'Jinen Kamdar',
    linearDisplayName: 'jinen',
    linearEmail: 'jinen@gather.town',
    slackUserId: 'U03CCF3PYLV',
    slackUserName: 'jinen',
    slackRealName: 'Jinen Kamdar',
    slackEmail: 'jinen@gather.town',
  },
  {
    linearId: '445582b7-573b-4aa4-9f1f-4e9904ec002e',
    linearName: 'Quan Li',
    linearDisplayName: 'quan',
    linearEmail: 'quan@gather.town',
    slackUserId: 'U030QTLRQJV',
    slackUserName: 'quan',
    slackRealName: 'Quan Li',
    slackEmail: 'quan@gather.town',
  },
  {
    linearId: 'b546456d-3f75-4781-a168-56d05dc374e7',
    linearName: 'Andrea Margarita Zevallos Cepulo',
    linearDisplayName: 'sazdx',
    linearEmail: 'sazdx@gather.town',
    slackUserId: 'U01MMG10K1B',
    slackUserName: 'sazdx',
    slackRealName: 'Andrea Margarita Zevallos Cepulo',
    slackEmail: 'sazdx@gather.town',
  },
  {
    linearId: '51c3230e-2da4-4ecd-a98e-c080a6d85de7',
    linearName: 'Evangeline Cheng',
    linearDisplayName: 'evangeline',
    linearEmail: 'evangeline@gather.town',
    slackUserId: 'U02S5GN2DQD',
    slackUserName: 'evangeline',
    slackRealName: 'Evangeline Cheng',
    slackEmail: 'evangeline@gather.town',
  },
  {
    linearId: 'd7b66bc6-566c-4e39-8d3f-c16f416935c4',
    linearName: 'Achilleas Triantafyllou',
    linearDisplayName: 'achilleas',
    linearEmail: 'achilleas@gather.town',
    slackUserId: 'U02DF8N2RK4',
    slackUserName: 'achilleas',
    slackRealName: 'Achilleas Triantafyllou',
    slackEmail: 'achilleas@gather.town',
  },
  {
    linearId: 'fcec37a3-3e23-4235-b2a0-66fc38e9f3d8',
    linearName: 'Gianluca Esposito',
    linearDisplayName: 'gianluca',
    linearEmail: 'gianluca@gather.town',
    slackUserId: 'U02A4LGUBGX',
    slackUserName: 'gianluca',
    slackRealName: 'Gianluca Esposito',
    slackEmail: 'gianluca@gather.town',
  },
  {
    linearId: '77222287-ba34-46bc-b360-d5be5b4c009b',
    linearName: 'David Orr',
    linearDisplayName: 'david',
    linearEmail: 'david@gather.town',
    slackUserId: 'U025PUZ532N',
    slackUserName: 'david',
    slackRealName: 'David Orr',
    slackEmail: 'david@gather.town',
  },
  {
    linearId: 'df9d1c77-2cc0-4eb2-b08f-de8d19b79be2',
    linearName: 'Clinton Geissler',
    linearDisplayName: 'clinton',
    linearEmail: 'clinton@gather.town',
    slackUserId: 'U01UL4TEYNA',
    slackUserName: 'clinton',
    slackRealName: 'Clint',
    slackEmail: 'clinton@gather.town',
  },
  {
    linearId: 'bb4e4a79-3200-4437-b1ab-3ffb0b18dca8',
    linearName: 'Emily Hu',
    linearDisplayName: 'emily',
    linearEmail: 'emily@gather.town',
    slackUserId: 'U01UNFLR6F2',
    slackUserName: 'emily',
    slackRealName: 'Emily Hu',
    slackEmail: 'emily@gather.town',
  },
  {
    linearId: '27dadd11-5343-40db-b9be-eba6f7874346',
    linearName: 'Ashley Kalley',
    linearDisplayName: 'ashley',
    linearEmail: 'ashley@gather.town',
    slackUserId: 'U01SJ6L8JNS',
    slackUserName: 'ashley',
    slackRealName: 'Ashley Kalley',
    slackEmail: 'ashley@gather.town',
  },
  {
    linearId: '5dc26597-bb96-4ecb-8650-58f820ee5f38',
    linearName: 'Daud Alzayer',
    linearDisplayName: 'daud',
    linearEmail: 'daud@gather.town',
    slackUserId: 'U01GFAMFY31',
    slackUserName: 'daud',
    slackRealName: 'Daud Alzayer',
    slackEmail: 'daud@gather.town',
  },
  {
    linearId: 'bf1b32df-c4f7-4df8-a2d2-a5392ff4cd11',
    linearName: 'Panagiotis Atmatzidis',
    linearDisplayName: 'panagiotis',
    linearEmail: 'panagiotis@gather.town',
    slackUserId: 'U01KFT6HUNS',
    slackUserName: 'panagiotis',
    slackRealName: 'Panagiotis Atmatzidis',
    slackEmail: 'panagiotis@gather.town',
  },
  {
    linearId: 'e66506fd-30a8-42d7-bd1d-c0ffb89bff01',
    linearName: 'Josh Conley',
    linearDisplayName: 'josh',
    linearEmail: 'josh@gather.town',
    slackUserId: 'U01J300APQB',
    slackUserName: 'josh',
    slackRealName: 'Josh Conley',
    slackEmail: 'josh@gather.town',
  },
  {
    linearId: '51b51810-a5b5-4578-a95e-3322a9b6eedf',
    linearName: 'Karen Ying',
    linearDisplayName: 'karen',
    linearEmail: 'karen@gather.town',
    slackUserId: 'U01HXG4L891',
    slackUserName: 'karen',
    slackRealName: 'Karen Ying',
    slackEmail: 'karen@gather.town',
  },
  {
    linearId: '066a4ebb-ce3a-470a-ab6a-b7361a6d8445',
    linearName: 'Daniel Kim',
    linearDisplayName: 'daniel',
    linearEmail: 'daniel@gather.town',
    slackUserId: 'U01HKFX90TW',
    slackUserName: 'daniel',
    slackRealName: 'Daniel Kim',
    slackEmail: 'daniel@gather.town',
  },
  {
    linearId: '6ce1dce5-d5b4-4e6f-a6bc-4beda94c5082',
    linearName: 'Kumail',
    linearDisplayName: 'kumail',
    linearEmail: 'kumail@gather.town',
    slackUserId: 'U0180NKJP89',
    slackUserName: 'kumail',
    slackRealName: 'Kumail Jaffer',
    slackEmail: 'kumail@gather.town',
  },
  {
    linearId: 'a1a2793d-f7c4-4420-88b4-8c3c097f5cd9',
    linearName: 'Phillip Wang',
    linearDisplayName: 'phillip',
    linearEmail: 'phillip@gather.town',
    slackUserId: 'U0177BP9CUX',
    slackUserName: 'phillip',
    slackRealName: 'Phillip Wang',
    slackEmail: 'phillip@gather.town',
  },
  {
    linearId: '7f7a9741-7051-4469-8d88-bb4e84a60400',
    linearName: 'Victor Zhou',
    linearDisplayName: 'vic',
    linearEmail: 'victor@gather.town',
    slackUserId: 'U01FGUX678C',
    slackUserName: 'victor',
    slackRealName: 'Victor Zhou',
    slackEmail: 'victor@gather.town',
  },
];
