"""Teamwork connector configuration keys.

Config classes are defined in teamwork_backfill_config.py.
"""

# Config keys (matching TypeScript)
TEAMWORK_ACCESS_TOKEN_KEY = "TEAMWORK_ACCESS_TOKEN"
TEAMWORK_API_DOMAIN_KEY = "TEAMWORK_API_DOMAIN"
TEAMWORK_INSTALLATION_ID_KEY = "TEAMWORK_INSTALLATION_ID"
TEAMWORK_USER_ID_KEY = "TEAMWORK_USER_ID"
TEAMWORK_USER_NAME_KEY = "TEAMWORK_USER_NAME"
TEAMWORK_TASKS_SYNCED_UNTIL_KEY = "TEAMWORK_TASKS_SYNCED_UNTIL"
TEAMWORK_FULL_BACKFILL_COMPLETE_KEY = "TEAMWORK_FULL_BACKFILL_COMPLETE"
TEAMWORK_TASKS_CURSOR_KEY = "TEAMWORK_TASKS_CURSOR"
