name: Assign Linear Ticket to Devin
description: Creates a branch, PR, generates a test plan, and assigns a Devin session for a Linear ticket

inputs:
  LINEAR_TICKET_ID:
    description: 'Linear Ticket ID (e.g., ENG-123 or UUID)'
    required: true
  BASE_BRANCH:
    description: 'Base branch for the PR'
    required: false
    default: 'main'
  LINEAR_API_KEY:
    description: 'Linear API key for authentication'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token for gh CLI and API operations'
    required: true
  CURSOR_API_KEY:
    description: 'Cursor API key for test plan generation'
    required: true
  DEVIN_API_KEY:
    description: 'Devin API key for session creation'
    required: true
  TEST_PLAN_PROMPT_FILE:
    description: 'Path to test plan prompt template (defaults to bundled prompt)'
    required: false
    default: ''
  IMPLEMENTATION_PROMPT_FILE:
    description: 'Path to Devin implementation prompt template (defaults to bundled prompt)'
    required: false
    default: ''
  REPO_RUNBOOK_FILE:
    description: 'Path to repo runbook file (default: .github/devin/runbook.md)'
    required: false
    default: '.github/devin/runbook.md'
  REPO_TESTING_ENTRY_POINTS_FILE:
    description: 'Path to repo-specific testing entry points guide (default: .github/test-plan/entrypoints.md)'
    required: false
    default: '.github/test-plan/entrypoints.md'

outputs:
  identifier:
    description: 'Linear ticket identifier'
    value: ${{ steps.linear.outputs.identifier }}
  title:
    description: 'Linear ticket title'
    value: ${{ steps.linear.outputs.title }}
  url:
    description: 'Linear ticket URL'
    value: ${{ steps.linear.outputs.url }}
  branch_name:
    description: 'Created branch name'
    value: ${{ steps.branch_pr.outputs.branch_name }}
  pr_number:
    description: 'PR number'
    value: ${{ steps.branch_pr.outputs.pr_number }}
  pr_url:
    description: 'PR URL'
    value: ${{ steps.branch_pr.outputs.pr_url }}
  session_id:
    description: 'Devin session ID'
    value: ${{ steps.devin.outputs.session_id }}
  session_url:
    description: 'Devin session URL'
    value: ${{ steps.devin.outputs.session_url }}

runs:
  using: composite
  steps:
    - name: Fetch Linear ticket details
      id: linear
      shell: bash
      env:
        LINEAR_API_KEY: ${{ inputs.LINEAR_API_KEY }}
        LINEAR_TICKET_ID: ${{ inputs.LINEAR_TICKET_ID }}
      run: ${{ github.action_path }}/scripts/fetch-linear-ticket.sh

    - name: Configure git
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create branch and PR
      id: branch_pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        IDENTIFIER: ${{ steps.linear.outputs.identifier }}
        TITLE: ${{ steps.linear.outputs.title }}
        URL: ${{ steps.linear.outputs.url }}
        BASE_BRANCH: ${{ inputs.BASE_BRANCH }}
      run: ${{ github.action_path }}/scripts/create-branch-and-pr.sh

    - name: Install Cursor CLI
      shell: bash
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> "$GITHUB_PATH"

    - name: Generate Test Plan
      id: test_plan
      shell: bash
      env:
        MODEL: auto
        CURSOR_API_KEY: ${{ inputs.CURSOR_API_KEY }}
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ steps.branch_pr.outputs.pr_number }}
        LINEAR_TICKET_ID: ${{ steps.linear.outputs.identifier }}
        LINEAR_TICKET_TITLE: ${{ steps.linear.outputs.title }}
        LINEAR_TICKET_URL: ${{ steps.linear.outputs.url }}
        PROMPT_FILE: ${{ inputs.TEST_PLAN_PROMPT_FILE || format('{0}/prompts/test-plan-prompt.md', github.action_path) }}
        REPO_TESTING_ENTRY_POINTS_FILE: ${{ inputs.REPO_TESTING_ENTRY_POINTS_FILE }}
      run: ${{ github.action_path }}/scripts/generate-test-plan.sh

    - name: Post test plan to PR
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PR_NUMBER: ${{ steps.branch_pr.outputs.pr_number }}
      run: ${{ github.action_path }}/scripts/post-pr-comment.sh @test_plan.md

    - name: Create Devin session
      id: devin
      shell: bash
      env:
        DEVIN_API_KEY: ${{ inputs.DEVIN_API_KEY }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ steps.branch_pr.outputs.pr_number }}
        PR_TITLE: '${{ steps.linear.outputs.identifier }}: ${{ steps.linear.outputs.title }}'
        PR_URL: ${{ steps.branch_pr.outputs.pr_url }}
        PR_BRANCH: ${{ steps.branch_pr.outputs.branch_name }}
        LINEAR_URL: ${{ steps.linear.outputs.url }}
        PROMPT_FILE: ${{ inputs.IMPLEMENTATION_PROMPT_FILE || format('{0}/prompts/devin-implementation-prompt.md', github.action_path) }}
        REPO_RUNBOOK_FILE: ${{ inputs.REPO_RUNBOOK_FILE }}
      run: ${{ github.action_path }}/scripts/create-devin-session.sh

    - name: Post Devin session link to PR
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PR_NUMBER: ${{ steps.branch_pr.outputs.pr_number }}
        SESSION_URL: ${{ steps.devin.outputs.session_url }}
        SESSION_ID: ${{ steps.devin.outputs.session_id }}
      run: |
        ${{ github.action_path }}/scripts/post-pr-comment.sh "## Devin Assigned

        A Devin session has been created to implement this ticket.

        **Session:** [$SESSION_ID]($SESSION_URL)

        Devin will:
        1. Review the Linear ticket and test plan
        2. Implement the feature
        3. Run tests and linting
        4. Push changes to this branch
        5. Mark the PR as ready for review when complete"
